INFO:root:Training model...
INFO:root:Collecting batch trajectories...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:Updating network parameter...
INFO:root:
INFO:root:------------ Episode: 2200 --------------
INFO:root:Mean return:          -1224.6348146315077
INFO:root:Mean policy loss:     -0.0002995082759298384
INFO:root:Mean value loss:      151817.296875
INFO:root:--------------------------------------------
INFO:root:
Traceback (most recent call last):
  File "/Volumes/Work Disk Janina Mattes/DEV/University/ASP/ml-explorer-drone/PPO/ppo_torch/ppo_continuous.py", line 1014, in <module>
    train(env,
  File "/Volumes/Work Disk Janina Mattes/DEV/University/ASP/ml-explorer-drone/PPO/ppo_torch/ppo_continuous.py", line 863, in train
    agent.learn()
  File "/Volumes/Work Disk Janina Mattes/DEV/University/ASP/ml-explorer-drone/PPO/ppo_torch/ppo_continuous.py", line 643, in learn
    df = self.stats_plotter.read_csv(CURR_TIME) # just select files from current date
  File "/Volumes/Work Disk Janina Mattes/DEV/University/ASP/ml-explorer-drone/PPO/ppo_torch/wrapper/stats_logger.py", line 47, in read_csv
    df = pd.concat((pd.read_csv(f) for f in all_files), ignore_index=True)
  File "/Users/janinaalicamattes/miniforge3/envs/pytorch-ppo-research/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/janinaalicamattes/miniforge3/envs/pytorch-ppo-research/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/Users/janinaalicamattes/miniforge3/envs/pytorch-ppo-research/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate